### ISSUE TITLE
IE doesn't show "Success: your edit has been sent to moderation" message

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#9]
We've added both the moderation and the visual editor extensions to our mediawiki installation and they are both working, however it seems like the moderation notices don't appear when the user is using the text editor.

Has anyone encountered similar before?

**Comment by edwardspec** [comment]
I re-tested Moderation with VisualEditor (1.27/1.28 with Firefox/Chrome).
Postedit notices ("Success: your edit has been sent to moderation [...]") are correctly displayed after making an edit in the "Edit source" mode (normal editing form).

Are the any errors/warning in the browser console?
After you save the edit and get redirected back to the article, is there "modqueued=1" in the URL?

**Comment by edwardspec** [comment]
The code that sends notification emails is completely independent from the frontend.
It works exactly the same for VisualEditor and for the usual "Edit source" mode.

**Comment by tansaku** [comment]
I'm not talking about email notifications - I'm talking about the popups that appear on the html pages when you save a page and the user is being moderated

**Comment by tansaku** [comment]
@edwardspec i.e. these:

![popup](https://www.dropbox.com/s/6o6w0elykokw0zh/Screenshot%202017-05-11%2017.46.02.png?dl=1)

**Comment by tansaku** [comment]
we are finding they work find with the visual editor, but don't seem to get displayed when using the default editor or wikieditor ...

**Comment by edwardspec** [comment]
I just re-tested them in 1.27/1.28 with Firefox/Chrome.
This message is shown after I save the edit in default editor ("Edit source" mode).

Are they any error messages in the browser console?
When you save an edit and are redirected back to the article, is there "modqueued=1" in the URL?

**Comment by tansaku** [comment]
it just worked fine for me creating a test page in the basic editor our staging instance:

![message displaying correctly](https://www.dropbox.com/s/9wrx8ordm0521v3/Screenshot%202017-05-15%2011.29.45.png?dl=1)

but there was one error in the console, and I notice that I was auto-logged out - see https://github.com/edwardspec/mediawiki-moderation/issues/11

**Comment by tansaku** [comment]
I re logged in and was pleased to see the moderation message still there and updated relating to having signed in:

![updated moderation message](https://www.dropbox.com/s/atwp0w1xtp429hd/Screenshot%202017-05-15%2011.32.01.png?dl=1)

**Comment by tansaku** [comment]
It also worked fine with the wikieditor on this instance.  Where I'm seeing the problem is on our main site which has the visual editor and SSL enabled.  I see the moderation popup with the visual editor there.

![moderation popup with visual editor on SSL enabled site](https://www.dropbox.com/s/5m6026m88717apj/Screenshot%202017-05-15%2011.40.36.png?dl=1)

it also worked in the wikieditor ... the issues I saw testing with users last week were on IE and safari ...

I just tested on IE11 on saucelabs using the wikieditor and saw the problem replicated:

![IE11 failing to display moderation notice](https://www.dropbox.com/s/baafdmfk9fg6jym/Screenshot%202017-05-15%2011.46.42.png?dl=1)

**Comment by tansaku** [comment]
the console was empty of errors in IE:

![console empty](https://www.dropbox.com/s/kvvoig1zfdieswo/Screenshot%202017-05-15%2011.48.02.png?dl=1)

**Comment by tansaku** [comment]
it worked fine on my local version of Safari ...

**Comment by edwardspec** [comment]
The error in the console (404 Not found) is irrelevant (it says "Test Page2 doesn't exist yet", which is true).

**Comment by edwardspec** [comment]
IE is notorious for having all kinds of problems due to not following standards.
I am surprised anyone still uses it in 2017.

I don't know what its problems are, nor can I investigate (as a Linux user).
You need to find someone familiar with IE to troubleshoot this.

**Comment by tansaku** [comment]
yes, ironically thousands of people are still required to use IE my their employer - in the case of our wiki lots of healthcare professionals and local authority employees in the UK.

I'm on OSX so can't investigate directly there, although saucelabs offers free sessions for open source projects to test on multiple browsers:

https://saucelabs.com

I've also got a windows rig to hand which I just fired up and replicated the issue on both our live and staging instance.  Inspecting the html on my windows box, IE11 just doesn't have the `postedit-container`div that would show the moderation message.

Is that being added to the page by javascript that might be failing?

As I say this is a fairly serious issues for thousands of our users so I am motivated in getting to the bottom of it.  Your help in understanding how the moderation message is added to the page is very much appreciated it - perhaps I will be able to fix it ...

**Comment by edwardspec** [comment]
> how the moderation message is added to the page

For the desktop (non-MobileFrontend) version, the following happens:

1) if URL contains modqueued=1, then  `mw.moderation.notifyQueued();` is called onload.
2) notifyQueued() calls `mw.moderation.notifyCb($div)` from [ext.moderation.notify.desktop.js].

You can type the following in the console to test if this works (in Firefox/Chrome, it does):
`mw.moderation.notifyCb( $('<div/>').append('Some text') )`

3) notifyCb invokes the usual notification from MediaWiki core (they work for sure, because they are used when Moderation is not installed):
`mw.hook( 'postEdit' ).fire( { message: $div } );`

**Comment by edwardspec** [comment]
By the way, does it work if you remove `'use strict';`? (from all *.js files under modules/).

**Comment by edwardspec** [comment]
I tested this with saucelabs.
Probably know the cause. Please stand by.

**Comment by edwardspec** [comment]
Should be fixed in 1.0.20 (https://github.com/edwardspec/mediawiki-moderation/commit/c0e2457ceec4b874dc034617b3e8a58316a8e5d0).
Please confirm it works.

**Comment by tansaku** [comment]
I have pulled your latest code onto staging and am now seeing moderation popups in IE - many thanks!

**Comment by tansaku** [comment]
although I'm still having the same trouble in production ... where I'm getting the following error

```
SCRIPT1004: Expected ';'
File; load.php, Line: 2, Column 329
```

production has visual editor and ssl enabled ... is there a test suite I can run ...?

I need to get a matching staging and production environments ...

**Comment by edwardspec** [comment]
If you click on these "Line: 2, Column 329", it should show the exact place in the JavaScript code where it occurs. That's how I found the previous error.

Next time you see this, let me know where it happens.

(MediaWiki combines/minifies all scripts, so column number doesn't help much)

At the moment, there is no JavaScript testsuite.
I agree that making some Selenium tests would be a good idea.

**Comment by tansaku** [comment]
thanks @edwardspec - I was just chatting with the mediawiki-visualeditor team about it - they said:

> [18:34] <+MatmaRex> tansaku: that error message doesn't look like it's getting stuck due to slow network or whatever, it looks like a syntax error in the script served by MediaWiki… as if it was corrupted it on the way or something? (or as if it was actually using a syntax that IE11 doesn't accept)
> [18:38] <+MatmaRex> tansaku: if you click on the "load.php (2,329)" in the error message, it will take you to the script that is failing. specifically, IE11 doesn't like this syntax: "for(pair of sendBody.entries())" in the module 'ext.moderation.ajaxhook' (this is part of some other extension you have installed, not VisualEditor)
> [18:38] <+MatmaRex> tansaku: for…of is a relatively new syntax and it won't work outside of most recent browsers. you should file a bug with whatever this extension is, asking them to support IE11.

**Comment by edwardspec** [comment]
Indeed, IE11 doesn't support `for ( A of B )` syntax.
Will rewrite this shortly.

**Comment by edwardspec** [comment]
IE11 doesn't even support FormData.entries().

**Comment by edwardspec** [comment]
This looks bad. In IE11, there is no way to read the contents of FormData at all.
https://msdn.microsoft.com/library/Hh772723#methods

In the current implementation, reading FormData is essential for ajaxhook (VisualEditor support in Moderation) to work.

**Comment by edwardspec** [comment]
Got an idea.
What we currently get from FormData, can be obtained by wrapping around mw.Api.prototype.api().
This should work in IE.

Investigating.

**Comment by tansaku** [comment]
oh dear - that's not so good ...

**Comment by edwardspec** [comment]
Fixed the FormData issue, but there is another problem:
in IE11, Object.defineProperty() doesn't make XMLHttpRequest.responseText writable.

Investigating further.

**Comment by tansaku** [comment]
@edwardspec anything I can do to help?

**Comment by edwardspec** [comment]
Should be fixed in 1.0.23.
Please confirm it works.

**Comment by tansaku** [comment]
hi @edwardspec - thanks for this - the moderation messages are now showing up in our production system in ie11.0.96 which is a big step forward.

Visual editor complete's it's loading cycle, but then it encounters a couple of errors in the console, and the editor appears, but everything is grayed out.

The two errors are a SyntaxError and an XML5632 error saying that only one root element is allowed - I've put the full details in this gist:

https://gist.github.com/tansaku/71994685d3b8da492cff598173eb5f4c

maybe this is a visual editor specific bug ... I'm going to create a fresh instance to help isolate what's going on.  Visual Editing still works on my mac ...

Great work getting the moderation messages working for this set up!

**Comment by tansaku** [comment]
I just tested the same IE on https://hlptest.miraheze.org/ where visual editor is enabled and it works fine, suggesting that this latest VE bug is still somehow related to our configuration - it might be something other than the moderation package, but perhaps the errors in the gist above make sense?

**Comment by edwardspec** [comment]
The exception happens in Extension:Cite. Please contact its authors.

The following may help them: https://phabricator.wikimedia.org/T138356 (this is how the same problem was fixed in Extension:Flow)

**Comment by edwardspec** [comment]
The exception happens in Extension:Cite.
The following may help them: https://phabricator.wikimedia.org/T138356 (this is how the same problem was fixed in Extension:Flow)

**Comment by tansaku** [comment]
Interesting - I just set up a fresh instance with VisualEditor and Cite, and it runs fine on IE11 - so I guess it's some interaction between VisualEditor, Cite, and Moderation that causes the problem no?

Or are you saying that Extension:Cite needs to change?

**Comment by tansaku** [comment]
I note that disabling the CiteExtension in our production instance does not fix the problem

**Comment by edwardspec** [comment]
The error is definitely in Cite.
Basically, the problem is:
1) VisualEditor supports "plugins" - they give it a piece of HTML.
2) Extension:Cite contains one of those plugins.
3) This plugin returns HTML like "`<p>something</p><p>else</p>`"
4) IE discards this HTML as incorrect because correct HTML must have one top element, e.g. "`<div><p>something</p><p>else</p></div>`".
5) The solution is to wrap HTML returned by Extension:Cite's plugin into one tag, like here: https://gerrit.wikimedia.org/r/#/c/307820/1/modules/flow/ui/widgets/editor/editors/mw.flow.ui.VisualEditorWidget.js
6) This error is in Extension:Cite and it should be fixed there.

You can't still have an error in "ext.cite.visualEditor" after disabling Cite. It's a cache issue.

**Comment by tansaku** [comment]
thanks, but so why does a fresh instance with Cite and VisualEditor work fine in IE11?  Or on Wikipedia where both Cite and VisualEditor are working (I just tested on IE11)?

If the problem is with Cite and VE combination and is unrelated to the Moderation extension, then why isn't it encountered in those other instances where Cite and VisualEditor are used together ...?

**Comment by tansaku** [comment]
I mentioned this thread here: https://www.mediawiki.org/wiki/Topic:Tqq4r90u8grsvm4q

**Comment by MatmaRex** [comment]
This isn't well documented (although technically it is mentioned here: https://doc.wikimedia.org/mediawiki-core/master/js/#!/api/mw.loader-event-resourceloader_exception), but `Exception in load-callback in module ext.cite.visualEditor` doesn't mean exception is in the 'ext.cite.visualEditor' code – it's an exception in the calling code, for example if you did:

```
mw.loader.using( 'ext.cite.visualEditor', function () {
    // Something here throws an exception
} );
```

**Comment by tansaku** [comment]
I also note (from @MatmaRex's input) that the problem is not ocurring on the main page, but on the Test_Page where my user has edits outstanding ... (i.e. in the moderation queue)

**Comment by tansaku** [comment]
I can confirm that the error only occurs when there are edits outstanding on the page

**Comment by tansaku** [comment]
I also tried turning on halting on all exceptions as suggested by MatmaRex:

![](https://i.imgur.com/8qoMW65.png)

and saw various exceptions (even when the VE editor loaded fine)

the following all raised syntax errors:

https://gist.github.com/tansaku/77f4186063a95352a81bca9e05a812ec

although I don't think they are related to this overall error that blocks the loading of the visual editor when moderated edits are pending ...

**Comment by edwardspec** [comment]
> I can confirm that the error only occurs when there are edits outstanding on the page

This situation (called "preloading") is handled by the code in [modules/visualeditor/preload.ve.js].

Does the error go away if you replace the following string:
`ret.visualeditor.content = ret2.visualeditor.content;`
with this:
`ret.visualeditor.content = '<div>' + ret2.visualeditor.content + '</div>';`
?

**Comment by edwardspec** [comment]
Reproduced the problem, investigating.

**Comment by edwardspec** [comment]
Should be fixed in 1.0.25.
Please confirm it works.

**Comment by tansaku** [comment]
many thanks @edwardspec - that's fixed it - really appreciate all your hard work.

would love to work towards some acceptance tests to keep all this in place - but super hard to config that to run the tests in IE11 without paying saucelabs or something ...

**Comment by edwardspec** [comment]
Doesn't IE11 support webdriver?

**Comment by edwardspec** [comment]
Closing this as completed.
I opened #13 for the task of creating a JavaScript testsuite.
